### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jfaler** [NadalVRoMa/PyLibGen#11]
I get the following error if I change libgen.io to libgen.is 

```
Traceback (most recent call last):
  File "pylibgen.py", line 307, in <module>
    raw_books, n_books = getSearchResults(search_term, page, sel_column)
  File "pylibgen.py", line 19, in getSearchResults
    print(books_found.group().upper())
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by AIvashka** [comment]
The same problem!

**Comment by dunemafia** [comment]
I had this same problem. I changed to libgen.li and now it displays the output correctly.
