### ISSUE TITLE
Entering 0 for the book number causes a traceback.

### ISSUE THREAD

**Issue by calebdavenport** [NadalVRoMa/PyLibGen#3]
### Behavior that occurs:
Program crashes when typing 0 for the book number.

### Behavior that should occur:
You should not be allowed to type zero; it should respond with `Not a valid option.`

### Version:
Python - 3.5.4
beautifulsoup4 - 4.4.1
tabulate - 0.7.5

### Logs:
```
$ python3 pylibgen.py zero
627 BOOKS FOUND
  #  Author                     Title                                               Publisher             Year    Lang    Ext    Size
---  -------------------------  --------------------------------------------------  --------------------  ------  ------  -----  ------
  1  David Darling              The Complete Book of Spaceflight: From Apollo 1 to  Wiley                 2002    En      pdf    10 Mb
  2  Lothar Gottsche            Hilbert schemes of zero-dimensional subschemes of   Springer-Verlag       1994    En      djvu   1 Mb
  ...
 24  Tang X.                    3/2-global attractivity of the zero solution of th                                En      pdf    348 kb
 25  Klinger R.                 A Basis that Reduces to Zero as many Curvature Com                        1991    En      pdf    171 kb

 Type # of book to download, q to quit or just press Enter to see more matches: 0
Downloading...
Traceback (most recent call last):
  File "/usr/lib64/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib64/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib64/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pylibgen.py", line 156, in <module>
    get_next_page = selectBook(books, mirrors, page, DOWNLOAD_PATH)
  File "pylibgen.py", line 82, in selectBook
    downloadBook(mirrors[choice]['io'], title, down_path)
  File "pylibgen.py", line 110, in downloadBook
    request.urlretrieve(download_url, filename=path)
  File "/usr/lib64/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib64/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by saifat29** [comment]
@calebdavenport I'm doing it.
